# Generated by Django 6.0.3 on 2026-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
