# Generated by Django 6.0.3 on 2026-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_author_id_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(default='about site', max_length=255)),
                ('about_text', models.CharField(max_length=10000)),
                ('about_mission', models.CharField(blank=True, max_length=10000)),
                ('about_vision', models.CharField(blank=True, max_length=10000)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
