# Generated by Django 6.0.3 on 2026-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_mission',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_vision',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
