# Generated by Django 6.0.3 on 2026-03-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_address',
            new_name='email',
        ),
    ]
