# Generated by Django 6.0.3 on 2026-03-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large')], default='medium', max_length=255),
        ),
    ]
