# Generated by Django 6.0.3 on 2026-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_usersettings_theme_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('francais', 'francais'), ('swahili', 'swahili')], default='english', max_length=255),
        ),
    ]
