# Generated by Django 6.0.3 on 2026-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_usersettings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('smaller', 'smaller'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('larger', 'larger')], default='medium', max_length=255),
        ),
    ]
