# Generated by Django 6.0.3 on 2026-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_usersettings_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='font_family',
            field=models.CharField(choices=[('sans-serif', 'sans-serif'), ('Courier New', 'Courier New'), ('Courier', 'Courier'), ('monospace', 'monospace'), ('Franklin Gothic Medium', 'Franklin Gothic Medium'), ('Arial Narrow', 'Arial Narrow'), ('Arial', 'Arial'), ('Gill Sans', 'Gill Sans'), ('Gill Sans MT', 'Gill Sans MT'), ('Calibri', 'Calibri'), ('Trebuchet MS', 'Trebuchet MS'), ('Segoe UI', 'Segoe UI'), ('Tahoma', 'Tahoma'), ('Geneva', 'Geneva'), ('Verdana', 'Verdana'), ('Helvetica', 'Helvetica'), ('Impact', 'Impact'), ('Haettenschweiler', 'Haettenschweiler'), ('Arial Narrow Bold', 'Arial Narrow Bold')], default='sans-serif', max_length=255),
        ),
    ]
